### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#2]

**Comment by soniCaH** [comment]
Gather fields that are needed upon registration here.

Registration:

Page 1:
- Username
- E-mail
- First Name
- Last Name

Page 2:
- Attend Saturday
- Attend Sunday
- BBQ
  -- Meat preference
- Experience Level (radio)
- Field of Interest (autocomplete - free tagging)
- Want to help
  -- Saturday and/or Sunday

Page 3:
- T-Shirt pref (radio)
- Twitter handle
- Privacy setting

---
- Company is never asked during registration but is a field (it is there when you edit your profile for example).
- Styling: previous button during registration

**Comment by soniCaH** [comment]
Should be checked, themed and doublechecked (OG automatic registration was a problem, see if all fields that we are interested in are there and themed and validated and available in the edit form and so on...)

**Comment by jummonk** [comment]
- Threw out the custom 'I will attend...' field and replaced it with the OG field so user automatically becomes member of the selected event. Also renamed the events so their titles has date in it.
- Themed the buttons.
