### ISSUE TITLE
1 Learn 2 Share 3 Get involved blocks on homepage

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#20]
![image](https://f.cloud.github.com/assets/3871797/692144/d0fc137a-dc02-11e2-90b9-434c951ea0af.png)

**Comment by soniCaH** [comment]
1 / 2 / 3 will become images probably instead of literally 1 - 2 - 3 ?

**Comment by g-raph** [comment]
![schermafbeelding 2013-06-25 om 14 32 02](https://f.cloud.github.com/assets/4610868/702436/44bbb360-dd93-11e2-9cc7-11c20d662f83.png)
