### ISSUE TITLE
1 Learn 2 Share 3 Get involved blocks LINKS 

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#23]
In the 3 blocks, add links where possible 

to attendees
to speakers
...

**Comment by g-raph** [comment]
Learn = page 'speakers' or 'program'?
Share = page 'attandees'?
Involve = page 'community'?

**Comment by g-raph** [comment]
Done.

Learn: links to /program
Share: links to /community/attendees
Involve: links to /organization
