### ISSUE TITLE
Speaker view

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#28]
![image](https://f.cloud.github.com/assets/3871797/692164/333747a6-dc05-11e2-8dd9-a1c4f03ee61e.png)

Important 

group by speaker (speakers with 2 sessions should not appear twice)

Info: two groupings. One on picture and one on name, this is necessary in case someone is speaker for more than one session. (See user drupalcamp as test example for this.)

**Comment by g-raph** [comment]
Ik heb de desktop-versie gethemed: http://dev.qandisa.be/speakers

Ik vind dat er wel wat meer info bijmag, zoals twitter, mail, ...

**Comment by g-raph** [comment]
Done.
