### ISSUE TITLE
News

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#30]
- New field (image)
- View modes
  - default (full node)
  - teaser (news overview - 8 col)
  - frontpage_latest (title, date, image, summary)
  - frontpage_teaser (title, (date,) summary)
- Views
  - View page "news_overview" (no menu item)
  - View block "news_latest_frontpage" 
    - Latest news item (1) on the left - frontpage_latest
    - 2 next news items on the right - frontpage_teaser
      (done with DS alternating view modes?)
    - Link to news_overview page

--> genre drupalcamp ghent (drupalcampgent.be)

one row on left side (2 on right side)

![image](https://f.cloud.github.com/assets/3871797/692169/b9a3afc8-dc05-11e2-9514-d7af9ab61111.png)

**Comment by soniCaH** [comment]
Closed unless additional theming is wanted
