### ISSUE TITLE
BBQ page

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#34]
Add some info about BBQ (time?)
Add a code block to this page counting down available places using the info from the user registrations.

**Comment by jummonk** [comment]
Have currently assigned this to Peggy: https://basecamp.com/1913353/projects/1637490-drupal-camp-leuven/todos/49844783-content-entry-bbq

**Comment by ghost** [comment]
i'll take this

**Comment by g-raph** [comment]
Themed.

**Comment by ghost** [comment]
die changes moeten overgezet worden naar de live-omgeving alhier: http://87.238.165.200/~dcleuven/?q=bbq

**Comment by ghost** [comment]
de image van de BBQ wordt niet geladen

**Comment by g-raph** [comment]
hey esther

die image is geladen met IMCE in de wysiwyg. Ik wou hem terug uploaden, maar krijg volgende foutmelding:

![schermafbeelding 2013-07-14 om 21 20 49](https://f.cloud.github.com/assets/4610868/794769/d8617bb8-ecbb-11e2-8c0b-eb9ed09c158d.png)

kan ik u ergens bereiken op IRC of skype?

**Comment by ghost** [comment]
skype
