### ISSUE TITLE
Attendees view

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#38]
Mention  of organization
sort alphabetically

**Comment by noneTaken** [comment]
TODO:
- Place block view with attendees somewhere on the site
- Maybe link to the organization

**Comment by soniCaH** [comment]
is er een verschil met #11 ?

**Comment by g-raph** [comment]
denk t niet :)

**Comment by noneTaken** [comment]
Closed #11 

TODO:
- Theming
  ...

**Comment by g-raph** [comment]
Themed.

Enkel nog links toevoegen aan naam/organization.

**Comment by drupalaar** [comment]
Mag niet zichtbaar zijn voor anonieme gebruikers (cfr privacy info op registratiepagina)
Experience Level wordt niet getoond.

**Comment by noneTaken** [comment]
- View heeft de filter: 'show my profile in attendees list ...'. Dit is een checkbox die de gebruiker kan aanvinken tijdens de registratie. 
- Experience level zou ik niet tonen op een overzicht pagina. Dit is niet nodig en de pagina wordt anders te druk. Indien iemand de kennis van een persoon wil weten, kan deze steeds door klikken naar een gebruikersprofiel.
