### ISSUE TITLE
Aligment logo loopt fout na herschikken menu

### ISSUE THREAD

**Issue by drupalaar** [jummonk/leuven2013.drupalcamp.be#42]
Ik heb Volunteers onder Community geschoven om aantal hoofdmenu-entries te beperken. Nu aligneert het logo niet meer correct.
Logo misschien verhuizen naar blauwe band eronder? Dan kan witte menubalk smaller, en staan er nog maar 1 logo?

**Comment by g-raph** [comment]
als het stoort dat er teveel menu-entries zijn, voor mij geen probleem, maar dan moet 'home' ook verdwijnen, zodat het menu terug in evenwicht is.

Het logo verhuizen vind ik geen goed idee.

Wat vindt de rest hierover?

Is er toevallig een IRC kanaal of Skype kanaal waarop we kunnen communiceren? Anders maak ik snel een groep aan op beiden...

**Comment by drupalaar** [comment]
Ik begrijp de estetische afweging ;-) al gaat voor mij gebruiksvriendelijkheid/eenvoud voor. Kan menu ook snel terug activeren. Ik wil je sterk werk niet teniet doen/moeilijker maken door mijn structuur-purisme.

**Comment by g-raph** [comment]
Heb wiki aangevuld met communicatie kanalen:

IRC-channel irc.freenode.net channel: #drupalcampleuven

SKYPE Gunter: gunnie007

**Comment by soniCaH** [comment]
ik ben ook voor "minder is beter", maar denk dat 3 langs elke kant nog wel binnen deze perken valt m.i.

**Comment by soniCaH** [comment]
Heb het even teruggeplaatst, voor mij is het zeker niet te veel, en layout zag er niet uit zo ;-)

**Comment by g-raph** [comment]
case closed.
