### ISSUE TITLE
Add google analytics by the time we go live

### ISSUE THREAD

**Issue by soniCaH** [jummonk/leuven2013.drupalcamp.be#43]
There is a google account and already one google analytics use case
By the time we release this "final" site, a new site should be added and the analytics should be added to the drupal site (tpl or module)

**Comment by soniCaH** [comment]
Will add the right code when we deploy to live

**Comment by ghost** [comment]
we allready have a working account, i'm the admin and so is info@drupalcamp.be, so yell if you need something you can't find.
