### ISSUE TITLE
Message after submitting contact is shown way too low on home

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#49]
Content region on home starts under page fold, so move drupal messages to header on homepage.

![screen shot 2013-07-02 at 10 46 58](https://f.cloud.github.com/assets/3871797/735435/222237aa-e2f4-11e2-857b-38328bd8fbe4.png)

**Comment by g-raph** [comment]
Fixed.

![schermafbeelding 2013-07-14 om 23 28 22](https://f.cloud.github.com/assets/4610868/794972/5c2ff144-eccc-11e2-848f-5416bd4cb5aa.png)
