### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#5]

**Comment by soniCaH** [comment]
![screen shot 2013-07-01 at 12 12 08](https://f.cloud.github.com/assets/789034/730106/8abe8a08-e249-11e2-9d13-be467721fe2f.png)

**Comment by g-raph** [comment]
Oplossing: niet direct van desktop naar mobile gaan, maar nog een tussenstap tablet toevoegen. Morgen werk ik van thuis uit en zal dit dan opnemen.

**Comment by soniCaH** [comment]
Alrighty! Je bent ook altijd welkom op de Amplexor Coding sprint morgen ;-)

**Comment by g-raph** [comment]
Fixed!
