### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by soniCaH** [jummonk/leuven2013.drupalcamp.be#52]
Badges (something users can put on their blog/site/profile) need to be created and the example code to include them should be provided on the website.

Which ones?
- I'm going to DrupalCamp Leuven
- I'm volunteering on DrupalCamp Leuven
- I'm sponsoring DrupalCamp Leuven
  ?
  Cfr http://drupalcampgent.be/nl/spread-word (website badges)

Assigning Gunter for the design, I (or someone else) can create the pages and codes

**Comment by noneTaken** [comment]
DONE:
- Page is created

TODO:
- Create badges
- Update page

**Comment by g-raph** [comment]
Done.
