### ISSUE TITLE
Header stylings

### ISSUE THREAD

**Issue by soniCaH** [jummonk/leuven2013.drupalcamp.be#53]
http://dev.qandisa.be/free-sponsorslots

h3 and h4 are totally not distinguishable from regular content

Also see #5

**Comment by drupalaar** [comment]
Ik heb h3 ook gebruikt op BBQ page. Met vette en procentje groter font ben ik content.

**Comment by g-raph** [comment]
Fixed:

![schermafbeelding 2013-07-09 om 18 44 30](https://f.cloud.github.com/assets/4610868/769503/e92b96da-e8b6-11e2-9562-82c998d3f189.png)
