### ISSUE TITLE
content input restrictions

### ISSUE THREAD

**Issue by ghost** [jummonk/leuven2013.drupalcamp.be#55]
Hey
I have about every possible role on the website but can't edit some content.
I checked permissions, access control, field access & rights but can't find what is wrong. Any ideas?

**Comment by soniCaH** [comment]
Any examples of pages/content you cannot edit?
Maybe you try to access OG specific content directly in the admin panel (no idea if this is possible here?)

**Comment by ghost** [comment]
sorry
http://dev.qandisa.be/node/77/edit - beer tour
http://dev.qandisa.be/node/8/edit - practical information

screenshot attached
![afbeelding 43](https://f.cloud.github.com/assets/4973065/769236/97933e00-e8b0-11e2-953b-a988058d383b.jpg)

**Comment by soniCaH** [comment]
Haaa, dat was dus al een gevolg van die Full HTML. User 1 kan Full HTML
aanmaken en dan kunnen alle andere users daar niet meer aan want niemand
anders (zelfs admin niet) heeft dat text format.
Zou opgelost moeten zijn voor die 2 nodes al iig.

From:  wwwonderland notifications@github.com
Reply-To:  "jummonk/leuven2013.drupalcamp.be"
<reply+i-16532552-e52ef765fd2f0e9f738c8d050d1d84f0204bffc2-789034@reply.gith
ub.com>
Date:  dinsdag 9 juli 2013 18:00
To:  "jummonk/leuven2013.drupalcamp.be"
leuven2013.drupalcamp.be@noreply.github.com
Cc:  Kevin Van Ransbeeck climacon@gmail.com
Subject:  Re: [leuven2013.drupalcamp.be] content input restrictions (#55)

sorry
http://dev.qandisa.be/node/77/edit - beer tour
http://dev.qandisa.be/node/8/edit - practical information

screenshot attached
 <https://f.cloud.github.com/assets/4973065/769236/97933e00-e8b0-11e2-953b-a
988058d383b.jpg> 

‹
Reply to this email directly or view it on GitHub
<https://github.com/jummonk/leuven2013.drupalcamp.be/issues/55#issuecomment-
20684634> .

**Comment by ghost** [comment]
Nice catch, daar zou ik niet aan gedacht hebben.
