### ISSUE TITLE
Fixes voor Gunter

### ISSUE THREAD

**Issue by soniCaH** [jummonk/leuven2013.drupalcamp.be#57]
Gelieve alle (kleinere) fixes hier te verzamelen voor Gunter

**Comment by ghost** [comment]
background-color transition op alles

**Comment by ghost** [comment]
http://dev.qandisa.be/practical-information -> h2 en h3 is even groot precies

**Comment by g-raph** [comment]
Register page buttons onderaan.

**Comment by g-raph** [comment]
http://dev.qandisa.be/propose-session: onderaan op mobile: opsomming links en tekst rechts

**Comment by henknuyttens** [comment]
op IPhone: sessions, how to step 2: tekst springt in onder de 2 van de OL

**Comment by henknuyttens** [comment]
Campus UZ Gasthuisberg toevoegen bij location (voor de verstrooiden onder ons)

**Comment by soniCaH** [comment]
http://dev.qandisa.be/program - heb de naam van de zaal er bijgekregen met wat foefelwerk, maar trekt nog op niet veel zo he ;-)

Heb voor schedule items een klasse toegevoegd zodat hier icons aan toegevoegd kunnen worden.

``` LESS
.schedule_item {
  // ICON PLACEMENT
  &.schedule_welcome {
    h3 { 
      // welcome icon 
    }
  }
  &.schedule_bbq {
    h3 { 
      // bbq icon
    }
  }
  &.schedule_coffee {
    h3 { 
      // coffee icon
    }
  }
  &.schedule_closing {
    h3 { 
      // closing icon
    }
  }
  &.schedule_lunch {
    h3 { 
      // lunch icon
    }
  }
  &.schedule_end {
    h3 { 
      // the final end icon
    }
  }
}
```

**Comment by g-raph** [comment]
- Zouden we de sponsors een detailpagina geven? Daarop staat enkel het logo en een link naar de website... Misschien beter om bij klik rechtstreeks naar hun website te surfen?
- De user-page zou meer aanklikbare info moeten hebben vind ik, zoals een link naar twitter / linkedin / facebook ??

**Comment by soniCaH** [comment]
Sponsorpagina zou ik wel houden, zeker voor een SmallFish zal dat nodig zijn om uit te leggen wie ze zijn en al
En wordt het niet wat veel informatie vragen bij gebruiker? Nu wordt er Twitter enkel gevraagd (en dacht ook getoond als link als niemand dat verwijderd heeft)
