### ISSUE TITLE
Dropsolid logo in footer aanpassen

### ISSUE THREAD

**Issue by nleroy** [jummonk/leuven2013.drupalcamp.be#58]
Alle logo's staan daar in wit en bij mouse over een kleur versie. Bij dropsolid blijft het een zwart/wit versie. Kan dit nog aangepast worden. Gaat ook beter uitkomen voor het geheel.

**Comment by soniCaH** [comment]
da's zeker da, done

**Comment by nleroy** [comment]
Merci!
