### ISSUE TITLE
Social media on homepage

### ISSUE THREAD

**Issue by jummonk** [jummonk/leuven2013.drupalcamp.be#8]
See DrupalCon Prague but with our look and feel

In right sidebar

![image](https://f.cloud.github.com/assets/3871797/692162/fb176202-dc04-11e2-9e00-c7a3493b8077.png)

**Comment by soniCaH** [comment]
The block has been added with classes to style each icon

``` Less
#block-leuven2013-social-social-sidebar {
  .social-icon {
    &.icon-facebook {}
    &.icon-twitter {}
    &.icon-drupalorg {}
  }
}
```

Links are "hardcoded"
Fancier images are probably wanted (hover, sprite...), so I'm assigning this one to Gunter

**Comment by soniCaH** [comment]
Basic Blue icons added and linked. CSS Transition effect on hover added.
Images subject to change as they are pretty "clean". A grunge effect like Drupalcon prague should pimp them a bit up (although we don't want to copy their style completely)

**Comment by g-raph** [comment]
Nice module! I've themed the social block in sidebar.
